#! /bin/bash

cd ./Riemann_solver/
gcc -c ./Riemann_solver_exact.c -g
gcc -c ./Riemann_solver_Toro.c -I ../ -g
gcc -c ./linear_GRP_solver.c -I ../ -g
gcc -c ./linear_GRP_solver_Li.c -I ../ -g
gcc -c ./GRPSUB.c -I ../ -g


ar crv Riemann_solver.a Riemann_solver_exact.o Riemann_solver_Toro.o linear_GRP_solver.o linear_GRP_solver_Li.o GRPSUB.o
ranlib Riemann_solver.a
