#! /bin/bash

gcc -c ./MainEngine.c -I ../file_io/inc/  -g
gcc -o MainEngine\
       MainEngine.o\
       FD_WENO/FD_WENO.a\
       GRP_fix/GRP_fix.a\
       GRP_HWENO_fix/GRP_HWENO_fix.a\
       reconstruction/reconstruction.a\
       file_io_local/file_o_local.o\
       ../file_io/file_io.a\
       ../Riemann_solver/Riemann_solver.a\
       -lm


exit 0
