#! /bin/bash


cd ./reconstruction/
gcc -c ./GRP_minmod.c -I ../ -g
gcc -c ./local_WENO_3_inter_Z.c -I ../ -g
gcc -c ./local_WENO_5_inter.c -I ../ -g
gcc -c ./local_WENO_5_inter_Z.c -I ../ -g
gcc -c ./local_HWENO_5_inter.c -I ../ -g
gcc -c ./local_HWENO_5_inter_Z.c -I ../ -g
gcc -c ./WENO_3.c -I ../ -g
gcc -c ./WENO_5.c -I ../ -g
gcc -c ./HWENO_5.c -I ../ -g
gcc -c ./THINC.c -I ../ -g

ar crv reconstruction.a GRP_minmod.o \
                        local_WENO_3_inter_Z.o \
                        local_WENO_5_inter.o \
                        local_WENO_5_inter_Z.o \
                        local_HWENO_5_inter.o \
                        local_HWENO_5_inter_Z.o \
                        WENO_3.o \
                        WENO_5.o \
                        HWENO_5.o \
                        THINC.o
ranlib reconstruction.a
echo "-----------------"




cd ../GRP_fix/
gcc -c ./ADER2_fix.c    -I ../\
                        -I ../../file_io-new/inc/\
                        -I ../../Riemann_solver/inc/\
                        -g
gcc -c ./GRP2_fix.c    -I ../\
                       -I ../../file_io-new/inc/\
                       -I ../../Riemann_solver/inc/\
                       -g
gcc -c ./THINC_fix.c    -I ../\
                        -I ../../file_io-new/inc/\
                        -I ../../Riemann_solver/inc/\
                        -g

ar crv GRP_fix.a GRP2_fix.o ADER2_fix.o THINC_fix.o
ranlib GRP_fix.a
echo "-----------------"


cd ../GRP_WENO_fix/
gcc -c ./GRP3_WENO3_fix.c    -I ../\
                             -I ../../file_io/inc/\
                             -I ../../Riemann_solver/inc/\
                             -g
gcc -c ./GRP3_WENO5_fix.c    -I ../\
                             -I ../../file_io/inc/\
                             -I ../../Riemann_solver/inc/\
                             -g
gcc -c ./GRP4_WENO5_fix.c    -I ../\
                             -I ../../file_io/inc/\
                             -I ../../Riemann_solver/inc/\
                             -g
gcc -c ./GRP5_WENO5_fix.c    -I ../\
                             -I ../../file_io/inc/\
                             -I ../../Riemann_solver/inc/\
                             -g

ar crv GRP_WENO_fix.a GRP3_WENO3_fix.o GRP3_WENO5_fix.o GRP4_WENO5_fix.o GRP5_WENO5_fix.o
ranlib GRP_WENO_fix.a
echo "-----------------"


cd ../GRP_HWENO_fix/
gcc -c ./ADER4_HWENO5_fix.c    -I ../\
                               -I ../../file_io-new/inc/\
                               -I ../../Riemann_solver/inc/\
                               -g
gcc -c ./GRP4_HWENO5_fix.c    -I ../\
                              -I ../../file_io-new/inc/\
                              -I ../../Riemann_solver/inc/\
                              -g
gcc -c ./GRP4_minmod_fix.c    -I ../\
                              -I ../../file_io-new/inc/\
                              -I ../../Riemann_solver/inc/\
                              -g

ar crv GRP_HWENO_fix.a GRP4_HWENO5_fix.o GRP4_minmod_fix.o ADER4_HWENO5_fix.o
ranlib GRP_HWENO_fix.a
echo "-----------------"


cd ../FD_WENO/
gcc -c ./FV_WENO_fix.c    -I ../\
                          -I ../../file_io-new/inc/\
                          -I ../../Riemann_solver/inc/\
                          -g
gcc -c ./LF4_WENO_fix.c    -I ../\
                           -I ../../file_io-new/inc/\
                           -I ../../Riemann_solver/inc/\
                           -g
gcc -c ./RF4_WENO_fix.c    -I ../\
                           -I ../../file_io-new/inc/\
                           -I ../../Riemann_solver/inc/\
                           -g
gcc -c ./flux_RF.c         -g

ar crv FD_WENO.a FV_WENO_fix.o RF4_WENO_fix.o flux_RF.o LF4_WENO_fix.o
ranlib FD_WENO.a
echo "-----------------"


exit 0
