#! /bin/bash

cd ./file_io_local/
gcc -c ./file_i_local.c   -I ../../file_io-new/inc/\
                          -I ../\
                          -g
gcc -c ./file_o_local.c   -I ../../file_io-new/inc/\
                          -I ../\
                          -g

ar crv file_io_local.a file_i_local.o  file_o_local.o \

exit 0
